name: flutter_audio_player_library
description: >
  Biblioteca Flutter para reprodução de áudio com playlist, controles de reprodução,
  seek e navegação entre faixas.
version: 1.0.9
homepage: https://github.com/ildopetrijunior/flutter_audio_player_library
repository: https://github.com/ildopetrijunior/flutter_audio_player_library

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.18 
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: